from typing import List, TypedDict

from .Names import ItemName
from .Names import LocationName


class LocationInfo(TypedDict):
    id: int
    name: str
    needs: List[str]


location_table: List[LocationInfo] = [
    {"id": 2, "name": LocationName.Story.Meet.Tails, "needs": []},
    {"id": 3, "name": LocationName.Story.Meet.Knuckles, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 4, "name": LocationName.Story.Meet.Amy, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 5, "name": LocationName.Story.Meet.Gamma,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 6, "name": LocationName.Story.Meet.Big,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},

    {"id": 10, "name": LocationName.Sonic.Upgrades.LightShoes, "needs": []},
    {"id": 11, "name": LocationName.Sonic.Upgrades.CrystalRing, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 12, "name": LocationName.Sonic.Upgrades.AncientLight, "needs": [ItemName.Sonic.LightShoes]},

    {"id": 20, "name": LocationName.Tails.Upgrades.JetAnkle, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 21, "name": LocationName.Tails.Upgrades.RhythmBadge, "needs": [ItemName.Tails.StoryUnlock]},

    {"id": 30, "name": LocationName.Knuckles.Upgrades.ShovelClaw, "needs": [ItemName.Knuckles.StoryUnlock]},
    {"id": 31, "name": LocationName.Knuckles.Upgrades.FightingGloves,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},

    {"id": 40, "name": LocationName.Amy.Upgrades.LongHammer, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 41, "name": LocationName.Amy.Upgrades.WarriorFeather, "needs": [ItemName.Amy.StoryUnlock]},

    {"id": 50, "name": LocationName.Gamma.Upgrades.LaserBlaster,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 51, "name": LocationName.Gamma.Upgrades.JetBooster, "needs": [ItemName.Gamma.StoryUnlock]},

    {"id": 60, "name": LocationName.Big.Upgrades.LifeBelt, "needs": [ItemName.Big.StoryUnlock]},
    {"id": 61, "name": LocationName.Big.Upgrades.PowerRod, "needs": [ItemName.Big.StoryUnlock]},

    {"id": 1000, "name": LocationName.Sonic.EmeraldCoast.A, "needs": []},
    {"id": 1001, "name": LocationName.Sonic.EmeraldCoast.B, "needs": []},
    {"id": 1002, "name": LocationName.Sonic.EmeraldCoast.C, "needs": []},
    {"id": 1100, "name": LocationName.Sonic.WindyValley.A, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1101, "name": LocationName.Sonic.WindyValley.B, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1102, "name": LocationName.Sonic.WindyValley.C, "needs": []},
    {"id": 1200, "name": LocationName.Sonic.Casinopolis.A, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1201, "name": LocationName.Sonic.Casinopolis.B, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1202, "name": LocationName.Sonic.Casinopolis.C, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1300, "name": LocationName.Sonic.IceCap.A, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1301, "name": LocationName.Sonic.IceCap.B, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1302, "name": LocationName.Sonic.IceCap.C, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1400, "name": LocationName.Sonic.TwinklePark.A, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1401, "name": LocationName.Sonic.TwinklePark.B, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1402, "name": LocationName.Sonic.TwinklePark.C, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1500, "name": LocationName.Sonic.SpeedHighway.A, "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1501, "name": LocationName.Sonic.SpeedHighway.B, "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1502, "name": LocationName.Sonic.SpeedHighway.C, "needs": [ItemName.Sonic.LightShoes]},
    {"id": 1600, "name": LocationName.Sonic.RedMountain.A,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1601, "name": LocationName.Sonic.RedMountain.B,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1602, "name": LocationName.Sonic.RedMountain.C,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1700, "name": LocationName.Sonic.SkyDeck.A,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1701, "name": LocationName.Sonic.SkyDeck.B,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1702, "name": LocationName.Sonic.SkyDeck.C,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1800, "name": LocationName.Sonic.LostWorld.A,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1801, "name": LocationName.Sonic.LostWorld.B,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1802, "name": LocationName.Sonic.LostWorld.C,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1900, "name": LocationName.Sonic.FinalEgg.A,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1901, "name": LocationName.Sonic.FinalEgg.B,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},
    {"id": 1902, "name": LocationName.Sonic.FinalEgg.C,
     "needs": [ItemName.Sonic.LightShoes, ItemName.Sonic.AncientLight]},

    {"id": 2000, "name": LocationName.Tails.WindyValley.A, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2001, "name": LocationName.Tails.WindyValley.B, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2002, "name": LocationName.Tails.WindyValley.C, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2100, "name": LocationName.Tails.Casinopolis.A, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2101, "name": LocationName.Tails.Casinopolis.B, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2102, "name": LocationName.Tails.Casinopolis.C, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2200, "name": LocationName.Tails.IceCap.A, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2201, "name": LocationName.Tails.IceCap.B, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2202, "name": LocationName.Tails.IceCap.C, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2300, "name": LocationName.Tails.SkyDeck.A, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2301, "name": LocationName.Tails.SkyDeck.B, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2302, "name": LocationName.Tails.SkyDeck.C, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2400, "name": LocationName.Tails.SpeedHighway.A, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2401, "name": LocationName.Tails.SpeedHighway.B, "needs": [ItemName.Tails.StoryUnlock]},
    {"id": 2402, "name": LocationName.Tails.SpeedHighway.C, "needs": [ItemName.Tails.StoryUnlock]},

    {"id": 3000, "name": LocationName.Knuckles.SpeedHighway.A, "needs": [ItemName.Knuckles.StoryUnlock]},
    {"id": 3001, "name": LocationName.Knuckles.SpeedHighway.B, "needs": [ItemName.Knuckles.StoryUnlock]},
    {"id": 3002, "name": LocationName.Knuckles.SpeedHighway.C, "needs": [ItemName.Knuckles.StoryUnlock]},
    {"id": 3100, "name": LocationName.Knuckles.Casinopolis.A, "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3101, "name": LocationName.Knuckles.Casinopolis.B, "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3102, "name": LocationName.Knuckles.Casinopolis.C, "needs": [ItemName.Knuckles.StoryUnlock]},
    {"id": 3200, "name": LocationName.Knuckles.RedMountain.A,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3201, "name": LocationName.Knuckles.RedMountain.B,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3202, "name": LocationName.Knuckles.RedMountain.C,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3300, "name": LocationName.Knuckles.LostWorld.A,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3301, "name": LocationName.Knuckles.LostWorld.B,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3302, "name": LocationName.Knuckles.LostWorld.C,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3400, "name": LocationName.Knuckles.SkyDeck.A,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3401, "name": LocationName.Knuckles.SkyDeck.B,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},
    {"id": 3402, "name": LocationName.Knuckles.SkyDeck.C,
     "needs": [ItemName.Knuckles.StoryUnlock, ItemName.Knuckles.ShovelClaw]},

    {"id": 4000, "name": LocationName.Amy.TwinklePark.A, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4001, "name": LocationName.Amy.TwinklePark.B, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4002, "name": LocationName.Amy.TwinklePark.C, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4100, "name": LocationName.Amy.HotShelter.A, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4101, "name": LocationName.Amy.HotShelter.B, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4102, "name": LocationName.Amy.HotShelter.C, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4200, "name": LocationName.Amy.FinalEgg.A, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4201, "name": LocationName.Amy.FinalEgg.B, "needs": [ItemName.Amy.StoryUnlock]},
    {"id": 4202, "name": LocationName.Amy.FinalEgg.C, "needs": [ItemName.Amy.StoryUnlock]},

    {"id": 5000, "name": LocationName.Gamma.FinalEgg.A, "needs": [ItemName.Gamma.StoryUnlock]},
    {"id": 5001, "name": LocationName.Gamma.FinalEgg.B, "needs": [ItemName.Gamma.StoryUnlock]},
    {"id": 5002, "name": LocationName.Gamma.FinalEgg.C, "needs": [ItemName.Gamma.StoryUnlock]},
    {"id": 5100, "name": LocationName.Gamma.EmeraldCoast.A, "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5101, "name": LocationName.Gamma.EmeraldCoast.B, "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5102, "name": LocationName.Gamma.EmeraldCoast.C, "needs": [ItemName.Gamma.StoryUnlock]},
    {"id": 5200, "name": LocationName.Gamma.WindyValley.A,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5201, "name": LocationName.Gamma.WindyValley.B,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5202, "name": LocationName.Gamma.WindyValley.C,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5300, "name": LocationName.Gamma.RedMountain.A,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5301, "name": LocationName.Gamma.RedMountain.B,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5302, "name": LocationName.Gamma.RedMountain.C,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5400, "name": LocationName.Gamma.HotShelter.A,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5401, "name": LocationName.Gamma.HotShelter.B,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},
    {"id": 5402, "name": LocationName.Gamma.HotShelter.C,
     "needs": [ItemName.Gamma.StoryUnlock, ItemName.Gamma.JetBooster]},

    {"id": 6000, "name": LocationName.Big.TwinklePark.A, "needs": [ItemName.Big.StoryUnlock]},
    {"id": 6001, "name": LocationName.Big.TwinklePark.B, "needs": [ItemName.Big.StoryUnlock]},
    {"id": 6002, "name": LocationName.Big.TwinklePark.C, "needs": [ItemName.Big.StoryUnlock]},
    {"id": 6100, "name": LocationName.Big.IceCap.A, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},
    {"id": 6101, "name": LocationName.Big.IceCap.B, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},
    {"id": 6102, "name": LocationName.Big.IceCap.C, "needs": [ItemName.Big.StoryUnlock]},
    {"id": 6200, "name": LocationName.Big.HotShelter.A, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},
    {"id": 6201, "name": LocationName.Big.HotShelter.B, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},
    {"id": 6202, "name": LocationName.Big.HotShelter.C, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},
    {"id": 6300, "name": LocationName.Big.EmeraldCoast.A, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},
    {"id": 6301, "name": LocationName.Big.EmeraldCoast.B, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},
    {"id": 6302, "name": LocationName.Big.EmeraldCoast.C, "needs": [ItemName.Big.StoryUnlock, ItemName.Big.LifeBelt]},

    {"id": 9999, "name": LocationName.Story.Fight.PerfectChaos},

]


def get_location_by_name(location_name: str) -> LocationInfo:
    for location in location_table:
        if location["name"] == location_name:
            return location
