from typing import List, TypedDict
from .Names import LocationName


class LocationInfo(TypedDict):
    id: int
    name: str
    needItems: List[int]


location_table: List[LocationInfo] = [
    {"id": 2, "name": LocationName.Story.Meet.Tails, "needItems": []},
    {"id": 3, "name": LocationName.Story.Meet.Knuckles, "needItems": [10]},
    {"id": 4, "name": LocationName.Story.Meet.Amy, "needItems": [10]},
    {"id": 5, "name": LocationName.Story.Meet.Gamma, "needItems": [10, 12]},
    {"id": 6, "name": LocationName.Story.Meet.Big, "needItems": [10, 12]},

    {"id": 10, "name": LocationName.Sonic.Upgrades.LightShoes, "needItems": []},
    {"id": 11, "name": LocationName.Sonic.Upgrades.CrystalRing, "needItems": [10]},
    {"id": 12, "name": LocationName.Sonic.Upgrades.AncientLight, "needItems": [10]},

    {"id": 20, "name": LocationName.Tails.Upgrades.JetAnkle, "needItems": [2]},
    {"id": 21, "name": LocationName.Tails.Upgrades.RhythmBadge, "needItems": [2]},

    {"id": 30, "name": LocationName.Knuckles.Upgrades.ShovelClaw, "needItems": [3]},
    {"id": 31, "name": LocationName.Knuckles.Upgrades.FightingGloves, "needItems": [3, 30]},

    {"id": 40, "name": LocationName.Amy.Upgrades.LongHammer, "needItems": [4]},
    {"id": 41, "name": LocationName.Amy.Upgrades.WarriorFeather, "needItems": [4]},

    {"id": 50, "name": LocationName.Gamma.Upgrades.LaserBlaster, "needItems": [5, 51]},
    {"id": 51, "name": LocationName.Gamma.Upgrades.JetBooster, "needItems": [5]},

    {"id": 60, "name": LocationName.Big.Upgrades.LifeBelt, "needItems": [6]},
    {"id": 61, "name": LocationName.Big.Upgrades.PowerRod, "needItems": [6]},

    {"id": 1000, "name": LocationName.Sonic.EmeraldCoast.A, "needItems": []},
    {"id": 1001, "name": LocationName.Sonic.EmeraldCoast.B, "needItems": []},
    {"id": 1002, "name": LocationName.Sonic.EmeraldCoast.C, "needItems": []},
    {"id": 1100, "name": LocationName.Sonic.WindyValley.A, "needItems": []},
    {"id": 1101, "name": LocationName.Sonic.WindyValley.B, "needItems": []},
    {"id": 1102, "name": LocationName.Sonic.WindyValley.C, "needItems": []},
    {"id": 1200, "name": LocationName.Sonic.Casinopolis.A, "needItems": [10]},
    {"id": 1201, "name": LocationName.Sonic.Casinopolis.B, "needItems": [10]},
    {"id": 1202, "name": LocationName.Sonic.Casinopolis.C, "needItems": [10]},
    {"id": 1300, "name": LocationName.Sonic.IceCap.A, "needItems": [10]},
    {"id": 1301, "name": LocationName.Sonic.IceCap.B, "needItems": [10]},
    {"id": 1302, "name": LocationName.Sonic.IceCap.C, "needItems": [10]},
    {"id": 1400, "name": LocationName.Sonic.TwinklePark.A, "needItems": [10]},
    {"id": 1401, "name": LocationName.Sonic.TwinklePark.B, "needItems": [10]},
    {"id": 1402, "name": LocationName.Sonic.TwinklePark.C, "needItems": [10]},
    {"id": 1500, "name": LocationName.Sonic.SpeedHighway.A, "needItems": [10]},
    {"id": 1501, "name": LocationName.Sonic.SpeedHighway.B, "needItems": [10]},
    {"id": 1502, "name": LocationName.Sonic.SpeedHighway.C, "needItems": [10]},
    {"id": 1600, "name": LocationName.Sonic.RedMountain.A, "needItems": [10, 12]},
    {"id": 1601, "name": LocationName.Sonic.RedMountain.B, "needItems": [10, 12]},
    {"id": 1602, "name": LocationName.Sonic.RedMountain.C, "needItems": [10, 12]},
    {"id": 1700, "name": LocationName.Sonic.SkyDeck.A, "needItems": [10, 12]},
    {"id": 1701, "name": LocationName.Sonic.SkyDeck.B, "needItems": [10, 12]},
    {"id": 1702, "name": LocationName.Sonic.SkyDeck.C, "needItems": [10, 12]},
    {"id": 1800, "name": LocationName.Sonic.LostWorld.A, "needItems": [10, 12]},
    {"id": 1801, "name": LocationName.Sonic.LostWorld.B, "needItems": [10, 12]},
    {"id": 1802, "name": LocationName.Sonic.LostWorld.C, "needItems": [10, 12]},
    {"id": 1900, "name": LocationName.Sonic.FinalEgg.A, "needItems": [10, 12]},
    {"id": 1901, "name": LocationName.Sonic.FinalEgg.B, "needItems": [10, 12]},
    {"id": 1902, "name": LocationName.Sonic.FinalEgg.C, "needItems": [10, 12]},
    {"id": 2000, "name": LocationName.Tails.WindyValley.A, "needItems": [2]},
    {"id": 2001, "name": LocationName.Tails.WindyValley.B, "needItems": [2]},
    {"id": 2002, "name": LocationName.Tails.WindyValley.C, "needItems": [2]},
    {"id": 2100, "name": LocationName.Tails.Casinopolis.A, "needItems": [2]},
    {"id": 2101, "name": LocationName.Tails.Casinopolis.B, "needItems": [2]},
    {"id": 2102, "name": LocationName.Tails.Casinopolis.C, "needItems": [2]},
    {"id": 2200, "name": LocationName.Tails.IceCap.A, "needItems": [2]},
    {"id": 2201, "name": LocationName.Tails.IceCap.B, "needItems": [2]},
    {"id": 2202, "name": LocationName.Tails.IceCap.C, "needItems": [2]},
    {"id": 2300, "name": LocationName.Tails.SkyDeck.A, "needItems": [2]},
    {"id": 2301, "name": LocationName.Tails.SkyDeck.B, "needItems": [2]},
    {"id": 2302, "name": LocationName.Tails.SkyDeck.C, "needItems": [2]},
    {"id": 2400, "name": LocationName.Tails.SpeedHighway.A, "needItems": [2]},
    {"id": 2401, "name": LocationName.Tails.SpeedHighway.B, "needItems": [2]},
    {"id": 2402, "name": LocationName.Tails.SpeedHighway.C, "needItems": [2]},
    {"id": 3000, "name": LocationName.Knuckles.SpeedHighway.A, "needItems": [3]},
    {"id": 3001, "name": LocationName.Knuckles.SpeedHighway.B, "needItems": [3]},
    {"id": 3002, "name": LocationName.Knuckles.SpeedHighway.C, "needItems": [3]},
    {"id": 3100, "name": LocationName.Knuckles.Casinopolis.A, "needItems": [3]},
    {"id": 3101, "name": LocationName.Knuckles.Casinopolis.B, "needItems": [3]},
    {"id": 3102, "name": LocationName.Knuckles.Casinopolis.C, "needItems": [3]},
    {"id": 3200, "name": LocationName.Knuckles.RedMountain.A, "needItems": [3, 30]},
    {"id": 3201, "name": LocationName.Knuckles.RedMountain.B, "needItems": [3, 30]},
    {"id": 3202, "name": LocationName.Knuckles.RedMountain.C, "needItems": [3, 30]},
    {"id": 3300, "name": LocationName.Knuckles.LostWorld.A, "needItems": [3, 30]},
    {"id": 3301, "name": LocationName.Knuckles.LostWorld.B, "needItems": [3, 30]},
    {"id": 3302, "name": LocationName.Knuckles.LostWorld.C, "needItems": [3, 30]},
    {"id": 3400, "name": LocationName.Knuckles.SkyDeck.A, "needItems": [3, 30]},
    {"id": 3401, "name": LocationName.Knuckles.SkyDeck.B, "needItems": [3, 30]},
    {"id": 3402, "name": LocationName.Knuckles.SkyDeck.C, "needItems": [3, 30]},
    {"id": 4000, "name": LocationName.Amy.TwinklePark.A, "needItems": [4]},
    {"id": 4001, "name": LocationName.Amy.TwinklePark.B, "needItems": [4]},
    {"id": 4002, "name": LocationName.Amy.TwinklePark.C, "needItems": [4]},
    {"id": 4100, "name": LocationName.Amy.HotShelter.A, "needItems": [4]},
    {"id": 4101, "name": LocationName.Amy.HotShelter.B, "needItems": [4]},
    {"id": 4102, "name": LocationName.Amy.HotShelter.C, "needItems": [4]},
    {"id": 4200, "name": LocationName.Amy.FinalEgg.A, "needItems": [4]},
    {"id": 4201, "name": LocationName.Amy.FinalEgg.B, "needItems": [4]},
    {"id": 4202, "name": LocationName.Amy.FinalEgg.C, "needItems": [4]},
    {"id": 5000, "name": LocationName.Gamma.FinalEgg.A, "needItems": [4]},
    {"id": 5001, "name": LocationName.Gamma.FinalEgg.B, "needItems": [4]},
    {"id": 5002, "name": LocationName.Gamma.FinalEgg.C, "needItems": [4]},
    {"id": 5100, "name": LocationName.Gamma.EmeraldCoast.A, "needItems": [5]},
    {"id": 5101, "name": LocationName.Gamma.EmeraldCoast.B, "needItems": [5]},
    {"id": 5102, "name": LocationName.Gamma.EmeraldCoast.C, "needItems": [5]},
    {"id": 5200, "name": LocationName.Gamma.WindyValley.A, "needItems": [5, 51]},
    {"id": 5201, "name": LocationName.Gamma.WindyValley.B, "needItems": [5, 51]},
    {"id": 5202, "name": LocationName.Gamma.WindyValley.C, "needItems": [5, 51]},
    {"id": 5300, "name": LocationName.Gamma.RedMountain.A, "needItems": [5, 51]},
    {"id": 5301, "name": LocationName.Gamma.RedMountain.B, "needItems": [5, 51]},
    {"id": 5302, "name": LocationName.Gamma.RedMountain.C, "needItems": [5, 51]},
    {"id": 5400, "name": LocationName.Gamma.HotShelter.A, "needItems": [5, 51]},
    {"id": 5401, "name": LocationName.Gamma.HotShelter.B, "needItems": [5, 51]},
    {"id": 5402, "name": LocationName.Gamma.HotShelter.C, "needItems": [5, 51]},
    {"id": 6000, "name": LocationName.Big.TwinklePark.A, "needItems": [10]},
    {"id": 6001, "name": LocationName.Big.TwinklePark.B, "needItems": [10]},
    {"id": 6002, "name": LocationName.Big.TwinklePark.C, "needItems": [10]},
    {"id": 6100, "name": LocationName.Big.IceCap.A, "needItems": [10]},
    {"id": 6101, "name": LocationName.Big.IceCap.B, "needItems": [10]},
    {"id": 6102, "name": LocationName.Big.IceCap.C, "needItems": [10]},
    {"id": 6200, "name": LocationName.Big.HotShelter.A, "needItems": [10]},
    {"id": 6201, "name": LocationName.Big.HotShelter.B, "needItems": [10]},
    {"id": 6202, "name": LocationName.Big.HotShelter.C, "needItems": [10]},
    {"id": 6300, "name": LocationName.Big.EmeraldCoast.A, "needItems": [10]},
    {"id": 6301, "name": LocationName.Big.EmeraldCoast.B, "needItems": [10]},
    {"id": 6302, "name": LocationName.Big.EmeraldCoast.C, "needItems": [10]},

    {"id": 9999, "name": LocationName.Story.Fight.PerfectChaos},

]
