from typing import List, TypedDict


class LocationInfo(TypedDict):
    id: int
    name: str
    needItems: List[int]


location_table: List[LocationInfo] = [
    {"id": 2, "name": "Meet Tails", "needItems": []},
    {"id": 3, "name": "Meet Knuckles", "needItems": [10]},
    {"id": 4, "name": "Meet Amy", "needItems": [10]},
    {"id": 5, "name": "Meet Gamma", "needItems": [10, 12]},
    {"id": 6, "name": "Meet Big", "needItems": [10, 12]},

    {"id": 10, "name": "Light shoes upgrade (Sonic)", "needItems": []},
    {"id": 11, "name": "Crystal ring upgrade (Sonic)", "needItems": [10]},
    {"id": 12, "name": "Ancient light upgrade (Sonic)", "needItems": [10]},

    {"id": 20, "name": "Jet Ankle upgrade (Tails)", "needItems": [2]},
    {"id": 21, "name": "Rhythm Badge upgrade (Tails)", "needItems": [2]},

    {"id": 30, "name": "Shovel claw upgrade (Knuckles)", "needItems": [3]},
    {"id": 31, "name": "Fighting gloves upgrade (Knuckles)", "needItems": [3, 30]},

    {"id": 40, "name": "Long Hammer upgrade (Amy)", "needItems": [4]},
    {"id": 41, "name": "Warrior feather upgrade (Amy)", "needItems": [4]},

    {"id": 50, "name": "Laser Blaster upgrade (Gamma)", "needItems": [5, 51]},
    {"id": 51, "name": "Jet booster upgrade (Gamma)", "needItems": [5]},

    {"id": 60, "name": "Life belt upgrade (Big)", "needItems": [6]},
    {"id": 61, "name": "Power rod upgrade (Big)", "needItems": [6]},

    # {"id": 1000, "name": "Emerald Coast (Sonic - Mission A)", "needItems": []},
    # {"id": 1001, "name": "Emerald Coast (Sonic - Mission B)", "needItems": []},
    {"id": 1002, "name": "Emerald Coast (Sonic - Mission C)", "needItems": []},
    # {"id": 1100, "name": "Windy Valley (Sonic - Mission A)", "needItems": []},
    # {"id": 1101, "name": "Windy Valley (Sonic - Mission B)", "needItems": []},
    {"id": 1102, "name": "Windy Valley (Sonic - Mission C)", "needItems": []},
    # {"id": 1200, "name": "Casinopolis (Sonic - Mission A)", "needItems": [10]},
    # {"id": 1201, "name": "Casinopolis (Sonic - Mission B)", "needItems": [10]},
    {"id": 1202, "name": "Casinopolis (Sonic - Mission C)", "needItems": [10]},
    # {"id": 1300, "name": "Ice Cap (Sonic - Mission A)", "needItems": [10]},
    # {"id": 1301, "name": "Ice Cap (Sonic - Mission B)", "needItems": [10]},
    {"id": 1302, "name": "Ice Cap (Sonic - Mission C)", "needItems": [10]},
    # {"id": 1400, "name": "Twinkle Park (Sonic - Mission A)", "needItems": [10]},
    # {"id": 1401, "name": "Twinkle Park (Sonic - Mission B)", "needItems": [10]},
    {"id": 1402, "name": "Twinkle Park (Sonic - Mission C)", "needItems": [10]},
    # {"id": 1500, "name": "Speed Highway (Sonic - Mission A)", "needItems": [10]},
    # {"id": 1501, "name": "Speed Highway (Sonic - Mission B)", "needItems": [10]},
    {"id": 1502, "name": "Speed Highway (Sonic - Mission C)", "needItems": [10]},
    # {"id": 1600, "name": "Red Mountain (Sonic - Mission A)", "needItems": [10, 12]},
    # {"id": 1601, "name": "Red Mountain (Sonic - Mission B)", "needItems": [10, 12]},
    {"id": 1602, "name": "Red Mountain (Sonic - Mission C)", "needItems": [10, 12]},
    # {"id": 1700, "name": "Sky Deck (Sonic - Mission A)", "needItems": [10, 12]},
    # {"id": 1701, "name": "Sky Deck (Sonic - Mission B)", "needItems": [10, 12]},
    {"id": 1702, "name": "Sky Deck (Sonic - Mission C)", "needItems": [10, 12]},
    # {"id": 1800, "name": "Lost World (Sonic - Mission A)", "needItems": [10, 12]},
    # {"id": 1801, "name": "Lost World (Sonic - Mission B)", "needItems": [10, 12]},
    {"id": 1802, "name": "Lost World (Sonic - Mission C)", "needItems": [10, 12]},
    # {"id": 1900, "name": "Final Egg (Sonic - Mission A)", "needItems": [10, 12]},
    # {"id": 1901, "name": "Final Egg (Sonic - Mission B)", "needItems": [10, 12]},
    {"id": 1902, "name": "Final Egg (Sonic - Mission C)", "needItems": [10, 12]},
    # {"id": 2000, "name": "Windy Valley (Tails - Mission A)", "needItems": [2]},
    # {"id": 2001, "name": "Windy Valley (Tails - Mission B)", "needItems": [2]},
    {"id": 2002, "name": "Windy Valley (Tails - Mission C)", "needItems": [2]},
    # {"id": 2100, "name": "Casinopolis (Tails - Mission A)", "needItems": [2]},
    # {"id": 2101, "name": "Casinopolis (Tails - Mission B)", "needItems": [2]},
    {"id": 2102, "name": "Casinopolis (Tails - Mission C)", "needItems": [2]},
    # {"id": 2200, "name": "Ice Cap (Tails - Mission A)", "needItems": [2]},
    # {"id": 2201, "name": "Ice Cap (Tails - Mission B)", "needItems": [2]},
    {"id": 2202, "name": "Ice Cap (Tails - Mission C)", "needItems": [2]},
    # {"id": 2300, "name": "Sky Deck (Tails - Mission A)", "needItems": [2]},
    # {"id": 2301, "name": "Sky Deck (Tails - Mission B)", "needItems": [2]},
    {"id": 2302, "name": "Sky Deck (Tails - Mission C)", "needItems": [2]},
    # {"id": 2400, "name": "Speed Highway (Tails - Mission A)", "needItems": [2]},
    # {"id": 2401, "name": "Speed Highway (Tails - Mission B)", "needItems": [2]},
    {"id": 2402, "name": "Speed Highway (Tails - Mission C)", "needItems": [2]},
    # {"id": 3000, "name": "Speed Highway (Knuckles - Mission A)", "needItems": [3]},
    # {"id": 3001, "name": "Speed Highway (Knuckles - Mission B)", "needItems": [3]},
    {"id": 3002, "name": "Speed Highway (Knuckles - Mission C)", "needItems": [3]},
    # {"id": 3100, "name": "Casinopolis (Knuckles - Mission A)", "needItems": [3]},
    # {"id": 3101, "name": "Casinopolis (Knuckles - Mission B)", "needItems": [3]},
    {"id": 3102, "name": "Casinopolis (Knuckles - Mission C)", "needItems": [3]},
    # {"id": 3200, "name": "Red Mountain (Knuckles - Mission A)", "needItems": [3, 30]},
    # {"id": 3201, "name": "Red Mountain (Knuckles - Mission B)", "needItems": [3, 30]},
    {"id": 3202, "name": "Red Mountain (Knuckles - Mission C)", "needItems": [3, 30]},
    # {"id": 3300, "name": "Lost World (Knuckles - Mission A)", "needItems": [3, 30]},
    # {"id": 3301, "name": "Lost World (Knuckles - Mission B)", "needItems": [3, 30]},
    {"id": 3302, "name": "Lost World (Knuckles - Mission C)", "needItems": [3, 30]},
    # {"id": 3400, "name": "Sky Deck (Knuckles - Mission A)", "needItems": [3, 30]},
    # {"id": 3401, "name": "Sky Deck (Knuckles - Mission B)", "needItems": [3, 30]},
    {"id": 3402, "name": "Sky Deck (Knuckles - Mission C)", "needItems": [3, 30]},
    # {"id": 4000, "name": "Twinkle Park (Amy - Mission A)", "needItems": [4]},
    # {"id": 4001, "name": "Twinkle Park (Amy - Mission B)", "needItems": [4]},
    {"id": 4002, "name": "Twinkle Park (Amy - Mission C)", "needItems": [4]},
    # {"id": 4100, "name": "Hot Shelter (Amy - Mission A)", "needItems": [4]},
    # {"id": 4101, "name": "Hot Shelter (Amy - Mission B)", "needItems": [4]},
    {"id": 4102, "name": "Hot Shelter (Amy - Mission C)", "needItems": [4]},
    # {"id": 4200, "name": "Final Egg (Amy - Mission A)", "needItems": [4]},
    # {"id": 4201, "name": "Final Egg (Amy - Mission B)", "needItems": [4]},
    {"id": 4202, "name": "Final Egg (Amy - Mission C)", "needItems": [4]},
    # {"id": 5000, "name": "Final Egg (Gamma - Mission A)", "needItems": [4]},
    # {"id": 5001, "name": "Final Egg (Gamma - Mission B)", "needItems": [4]},
    {"id": 5002, "name": "Final Egg (Gamma - Mission C)", "needItems": [4]},
    # {"id": 5100, "name": "Emerald Coast (Gamma - Mission A)", "needItems": [5]},
    # {"id": 5101, "name": "Emerald Coast (Gamma - Mission B)", "needItems": [5]},
    {"id": 5102, "name": "Emerald Coast (Gamma - Mission C)", "needItems": [5]},
    # {"id": 5200, "name": "Windy Valley (Gamma - Mission A)", "needItems": [5, 51]},
    # {"id": 5201, "name": "Windy Valley (Gamma - Mission B)", "needItems": [5, 51]},
    {"id": 5202, "name": "Windy Valley (Gamma - Mission C)", "needItems": [5, 51]},
    # {"id": 5300, "name": "Red Mountain (Gamma - Mission A)", "needItems": [5, 51]},
    # {"id": 5301, "name": "Red Mountain (Gamma - Mission B)", "needItems": [5, 51]},
    {"id": 5302, "name": "Red Mountain (Gamma - Mission C)", "needItems": [5, 51]},
    # {"id": 5400, "name": "Hot Shelter (Gamma - Mission A)", "needItems": [5, 51]},
    # {"id": 5401, "name": "Hot Shelter (Gamma - Mission B)", "needItems": [5, 51]},
    {"id": 5402, "name": "Hot Shelter (Gamma - Mission C)", "needItems": [5, 51]},
    # {"id": 6000, "name": "Twinkle Park (Big - Mission A)", "needItems": [6]},
    # {"id": 6001, "name": "Twinkle Park (Big - Mission B)", "needItems": [6]},
    {"id": 6002, "name": "Twinkle Park (Big - Mission C)", "needItems": [6]},
    # {"id": 6100, "name": "Ice Cap (Big - Mission A)", "needItems": [6]},
    # {"id": 6101, "name": "Ice Cap (Big - Mission B)", "needItems": [6]},
    {"id": 6102, "name": "Ice Cap (Big - Mission C)", "needItems": [6]},
    # {"id": 6200, "name": "Emerald Coast (Big - Mission A)", "needItems": [6]},
    # {"id": 6201, "name": "Emerald Coast (Big - Mission B)", "needItems": [6]},
    {"id": 6202, "name": "Emerald Coast (Big - Mission C)", "needItems": [6]},
    # {"id": 6300, "name": "Hot Shelter (Big - Mission A)", "needItems": [6, 60]},
    # {"id": 6301, "name": "Hot Shelter (Big - Mission B)", "needItems": [6, 60]},
    {"id": 6302, "name": "Hot Shelter (Big - Mission C)", "needItems": [6, 60]},

    {"id": 9999, "name": "Perfect Chaos Fight"},

]
