from . import Levels
from .ObjectTypes import ObjectType, SETObject
from .Names import REGION_INDICIES

DESIRABLE_OBJECTS_MAD_MATRIX  = [

    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_MAD_MATRIX, 165, "Warp Hole Into Green Tower"),
    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_MAD_MATRIX, 163, "Warp Hole Exit Of Green Tower"),
    SETObject(ObjectType.WARP_HOLE_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 312, "Warp Hole Exit Of Red Tower"),
    SETObject(ObjectType.WARP_HOLE_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 324, "Warp Hole Exit From Top Of Red Tower"),
    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_MAD_MATRIX, 107, "Warp Hole Into Yellow Tower"),

    SETObject(ObjectType.LIGHT_DASH_TRAIL_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 330, "Light Dash Near Green"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL, Levels.STAGE_MAD_MATRIX, 269, "Light Dash Into Red"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL, Levels.STAGE_MAD_MATRIX, 350, "Light Dash Out Of Red"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL, Levels.STAGE_MAD_MATRIX, 552, "Light Dash Within Yellow"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 328, 'Light Dash Near Red/Yellow',
              region=REGION_INDICIES.MAD_MATRIX_GUN),

    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_MAD_MATRIX, 500, "Shadow Box Near Red",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_MAD_MATRIX, 452, "Shadow Box Near Secret Door",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_MAD_MATRIX, 444, "Shadow Box Near Blue",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.ENERGY_CORE, Levels.STAGE_MAD_MATRIX, 443, "Hero Core",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_MAD_MATRIX, 332, "Secret Door",
              region=REGION_INDICIES.MAD_MATRIX_KEY_DOOR),

    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 570, '0', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 571, '1', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 7, '2', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 14, '3', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 15, '4', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 52, '5', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 53, '6', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 51, '7', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 50, '8', region=0),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_MAD_MATRIX, 347, '9', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 329, '10', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 502, '11', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 503, '12', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 327, '13', region=REGION_INDICIES.MAD_MATRIX_GUN),

    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 445, '15', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 451, '16', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 449, '17', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 450, '18', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 446, '19', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_MAD_MATRIX, 344, '20', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 511, '21', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 510, '22', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_WING, Levels.STAGE_MAD_MATRIX, 456, '23', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_WING, Levels.STAGE_MAD_MATRIX, 455, '24', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_MAD_MATRIX, 117, '25',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 119, '26',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 120, '27',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 151, '28',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 152, '29',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 181, '31',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 179, '32',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 182, '33',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 187, '34',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 188, '35',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 205, '36',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 206, '37',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 203, '38',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 238, '39',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_PROGRESSION),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 306, '40', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 308, '41', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 285, '42', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 286, '43', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 287, '44', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),

]