name: Test APWorld
on:
  push:
    branches: [shadow, future/*, ci]
  pull_request:
    branches: [shadow, future/*]


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/ap-tests@main
        with:
          apworld-path: worlds/shadow_the_hegdehog
          ap-version: '0.6.2'
          python-version: '3.12'